package com.example.paymentsystem.reconciliation.domain;

/** 대사 도메인에서 공유하는 상태와 분류를 정의한다. */
public final class ReconciliationEnums {
    private ReconciliationEnums() { }

    public enum MismatchType { WALLET_BALANCE_MISMATCH, PAYMENT_DEBIT_MISSING, PAYMENT_DEBIT_AMOUNT_MISMATCH, CANCEL_REFUND_MISSING, CANCEL_REFUND_AMOUNT_MISMATCH, CANCEL_ACCUMULATION_MISMATCH, CANCEL_AMOUNT_OVER_PAYMENT, PAYMENT_STUCK_PENDING, CANCEL_STUCK_PENDING, OUTBOX_STUCK_INIT, OUTBOX_STATE_MISMATCH, PG_TRANSACTION_ID_MISSING, PG_RESPONSE_LOG_MISSING }
    public enum Severity { MEDIUM, HIGH, CRITICAL }
    public enum RunStatus { RUNNING, COMPLETED, PARTIALLY_FAILED, FAILED }
    public enum CaseStatus { OPEN, INVESTIGATING, ACTION_REQUIRED, RESOLVED, FALSE_POSITIVE }
    public enum ActionType { START_INVESTIGATION, REQUEST_PG_CONFIRMATION, REQUEST_MANUAL_LEDGER_REVIEW, MARK_FALSE_POSITIVE, RECHECK, CONFIRM_RESOLVED }
    public enum TriggerType { SCHEDULED, MANUAL }
}
